version: '3.7'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: c-b
    volumes:
      - .:/app
    restart: unless-stopped
    tty: true
    privileged: true